FROM rockerextra/shiny-async-dev:3.4
MAINTAINER Jaehyeon Kim <dottami@gmail.com>

RUN rm -rf /etc/services.d/shiny-server \
    && mkdir -p /etc/services.d/javascript \
    && echo '#!/usr/bin/with-contenv sh \n python /home/rstudio/javascript/serve.py -p 7000 -d /home/rstudio/javascript' > /etc/services.d/javascript/run

