version: '3'
services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    command: /init
    privileged: true
    volumes:
      - ./api:/home/rstudio/api
      - ./javascript:/home/rstudio/javascript
      - ./shiny:/srv/shiny-server/shiny
    ports:
      - "8000:8000"
      - "7000:7000"
      - "8787:8787"
      - "3838:3838"

